# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'Congress' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Congress
  #$pod 'SlideMenuControllerSwift'
  # pod 'SwiftSpinner'
  # pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.0'
  target 'CongressTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CongressUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
